### PR TITLE
Update goreleaser step and docs publish

### PR DESCRIPTION
**Pull request by sudermanjr**
## Checklist
* [x] I have signed the CLA
* [x] I have updated/added any relevant documentation

### What's the goal of this PR?
Get to current standards

### What changes did you make?
Update circle config and goreleaser config

### CODE REVIEW

**Comment by sudermanjr** [comment]
Requires https://github.com/FairwindsOps/fairwindsops-infrastructure/pull/165 to be merged

**Comment by lucasreed** [comment]
I've made significant changes to the circleci config locally for my next PR. Would it be possible to wait on this?

**Comment by lucasreed** [comment]
Or I could incorporate them into my changes.

**Comment by sudermanjr** [comment]
I'm happy to just let you incorporate the changes if you want.

**Pull request closed without merging**
