### PR TITLE
Exit codes for exit status

### PR DESCRIPTION
**Pull request by endzyme**
For Issue #86 

    Added logic:

    - Exit codes
    - Exit after first error
    - bubble up the issue at the end of the message

### CODE REVIEW

**Comment by endzyme** [comment]
This change requires #112 and #111

**Comment by sudermanjr** [comment]
Ran a couple quick tests with this, and all the intended functionality seems to work really well.  Super exciting stuff and really awesome.  

Is the `continue-on-error` flag documented anywhere besides the help command?  Also, I think we might need to add a mention of these features to the changelog

**Comment by endzyme** [comment]
> Ran a couple quick tests with this, and all the intended functionality seems to work really well. Super exciting stuff and really awesome.
> 
> Is the `continue-on-error` flag documented anywhere besides the help command? Also, I think we might need to add a mention of these features to the changelog

Good catch - i'll publish changes in changelog and make sure it's mentioned in the Readme. I've opened #117 to help clean up docs holistically, but for now I'll add to README.md.

**Comment by endzyme** [comment]
@bambash @sudermanjr one last looksy before I merge this on through if you've got some time soon :) thanks again for all the testing

**Pull request merged**
