### PR TITLE
Interpolate Env Var in Chart Namespace

### PR DESCRIPTION
**Pull request by ejether**
This PR provides additional functionality to use environment variables in the namespace field of the chartblock.

### CODE REVIEW

**Comment by ejether** [comment]
Shoot, I can't see the failure logs.

**Comment by ejether** [comment]
🤔  I ran these locally and they did not fail. 
I cannot re-run them here though.

**Comment by ejether** [comment]
Following a conversation with @sudermanjr I locally tested a just built binary and was unable to reproduce the `error parsing yaml` issue. I added debut to one of the e2e tests so that I could see the full error, while that is building, I'll download the last binary and test it locally as well, (all darwin so far)

**Comment by ejether** [comment]
Downloaded reckoner darwin binary also fails locally with 
```
2020-12-15 08:30:11 C02DG0SRMD6R root[17958] DEBUG Traceback (most recent call last):
  File "reckoner/cli.py", line 108, in plot
    validate_course_file(course_file_stream)
  File "reckoner/schema_validator/course.py", line 54, in validate_course_file
    course_file_object = Handler.load(course_file)
  File "reckoner/yaml/handler.py", line 40, in load
    raise err
  File "reckoner/yaml/handler.py", line 32, in load
    y = cls.yaml.load(yaml_file)
  File "ruamel/yaml/main.py", line 341, in load
  File "ruamel/yaml/main.py", line 430, in get_constructor_parser
  File "ruamel/yaml/main.py", line 232, in constructor
  File "ruamel/yaml/constructor.py", line 75, in __init__
  File "ruamel/yaml/compat.py", line 258, in version_tnf
ImportError: cannot import name 'version_info' from 'ruamel.yaml' (/var/folders/02/sm4kz5k16nb594g_y7dc06dw0000gq/T/_MEIpyfvI8/ruamel/yaml/__init__.pyc)
```

**Comment by sudermanjr** [comment]
That's the same issue I'm running into on #256 as well. I'm attempting to update some of the build dependencies in that PR to fix it.

**Comment by ejether** [comment]
Since `ruamel` is such a problem child, I looked for a replacement and found `ruyaml`. It works locally, pushing here in 🤞 that it fixes the binary because it's linked better I think.

**Comment by ejether** [comment]
🥳

**Review by sudermanjr — APPROVED** [review]

**Pull request merged**
