### PR TITLE
Fix 248 chart relative to course file

### PR DESCRIPTION
**Pull request by ejether**
This PR Fixes https://github.com/FairwindsOps/reckoner/issues/248

This makes the chart repository path for local charts so that it is relative to the course file. The hooks were already handled in another way.

### CODE REVIEW

**Review by sudermanjr — APPROVED** [review]
Awesome possum. Thanks!

**Comment by ejether** [comment]
Hmm, looks like hooks execution might be bugged with this fix. Hold off.

**Comment by sudermanjr** [comment]
> Hmm, looks like hooks execution might be bugged with this fix. Hold off.

I would never merge before tests pass :-D

**Comment by ejether** [comment]
Done

**Pull request merged**
